apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: emailservice
  namespace: production
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: emailservice
  helmVersion: v3
  chart:
    git: git@gitlab.com:gugalaps/microservices-demo.git
    ref: master
    path: deploy/charts/emailservice
  values:
    image:
      repository: neogeowild/emailservice
      tag: v.0.0.1
