---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-iptables-tailer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: crb-kube-iptables-taile
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: kube-iptables-tailer
      namespace: kube-system