apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    app: frontend
  ports:
  - name: http
    port: {{ default "8080" .Values.service.port }}
    targetPort: {{ default "8080" .Values.service.targetPort }}
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ default "8081" .Values.service.nodePort }}
{{- end }}
