apiVersion: flagger.app/v1beta1
kind: AlertProvider
metadata:
  name: canary-info
  namespace: istio-system
spec:
  type: slack
  channel: canary-info
  username: flagger
  address: https://hooks.slack.com/services/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
