apiVersion: v1
kind: Pod
metadata:
  name: otus-les2-webapp-pod
  labels:
    component: otus-les2-label
spec:
  containers:
  - name: otus-les2
    image: neogeowild/otus_les2_webapp
    volumeMounts:
    - mountPath: /app
      name: cache-volume
  initContainers:
  - name: gen-index
    image: busybox
    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
    volumeMounts:
    - mountPath: /app
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
